version: "3"

services:
  app:
    container_name: portofolio
    build: 
      context: .
      network: host
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "4000:4000"
      - "35729:35729"